# Generated by Django 6.0.7 on 2026-07-30 16:00

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=20, verbose_name='平台类型')),
                ('version', models.CharField(max_length=50, verbose_name='版本号')),
                ('download_url', models.URLField(max_length=500, verbose_name='资源包/安装包URL')),
                ('is_forced', models.BooleanField(default=False, verbose_name='是否强制更新标识')),
                ('changelog', models.TextField(verbose_name='更新日志说明')),
            ],
            options={
                'verbose_name': '应用版本',
                'verbose_name_plural': '应用版本',
            },
        ),
        migrations.CreateModel(
            name='QuotaRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=50, unique=True, verbose_name='配置层级/专项')),
                ('monthly_quota', models.IntegerField(verbose_name='月度推送配额')),
            ],
            options={
                'verbose_name': '通知额度规则',
                'verbose_name_plural': '通知额度规则',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('work_id', models.CharField(max_length=50, unique=True, verbose_name='工号')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('role_id', models.CharField(max_length=50, verbose_name='角色ID')),
                ('organization', models.CharField(max_length=150, verbose_name='所属机构')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('level', models.CharField(max_length=50, verbose_name='发送层级')),
                ('status', models.CharField(choices=[('unread', '未读'), ('read', '已读')], default='unread', max_length=50, verbose_name='状态')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='发送人')),
            ],
            options={
                'verbose_name': '通知分发',
                'verbose_name_plural': '通知分发',
            },
        ),
        migrations.CreateModel(
            name='VisitRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=150, verbose_name='走访对象')),
                ('audio_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='音频文件URL')),
                ('original_text', models.JSONField(blank=True, null=True, verbose_name='原始转写文本')),
                ('ai_summary', models.TextField(blank=True, null=True, verbose_name='AI总结文本')),
                ('visit_time', models.DateTimeField(auto_now_add=True, verbose_name='走访时间')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='沟通时长')),
                ('business_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='关联业务类型')),
                ('status', models.CharField(choices=[('pending', '等待处理'), ('processing', '处理中'), ('success', '处理成功'), ('failed', '处理失败')], default='pending', max_length=20, verbose_name='处理状态')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '走访记录',
                'verbose_name_plural': '走访记录',
            },
        ),
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='事项内容')),
                ('trigger_type', models.CharField(max_length=50, verbose_name='触发类型')),
                ('trigger_value', models.CharField(blank=True, max_length=200, verbose_name='触发阈值')),
                ('status', models.CharField(choices=[('pending', '未办'), ('ongoing', '进行中'), ('closed', '闭环')], default='pending', max_length=20, verbose_name='状态')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
                ('visit_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.visitrecord', verbose_name='关联走访记录')),
            ],
            options={
                'verbose_name': '待办事项',
                'verbose_name_plural': '待办事项',
            },
        ),
    ]
