# Generated by Django 6.0.7 on 2026-07-17 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('unread', '未读'), ('read', '已读')], default='unread', max_length=50, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='visitrecord',
            name='ai_summary',
            field=models.TextField(blank=True, null=True, verbose_name='AI总结文本'),
        ),
        migrations.AlterField(
            model_name='visitrecord',
            name='audio_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='音频文件URL'),
        ),
        migrations.AlterField(
            model_name='visitrecord',
            name='business_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='关联业务类型'),
        ),
        migrations.AlterField(
            model_name='visitrecord',
            name='original_text',
            field=models.TextField(blank=True, null=True, verbose_name='原始转写文本'),
        ),
    ]
